apiVersion: v1
kind: Service
metadata:
  name: racklog
  namespace: racklog
  labels:
    app.kubernetes.io/name: racklog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: racklog
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
